name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - name: Download and Install Dart SDK
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.6-stable.tar.xz
          tar xf flutter_linux_3.10.6-stable.tar.xz
          export DART_SDK=$(pwd)/flutter_linux_3.10.6-stable.tar.xz
          export PATH="$PATH:$DART_SDK/bin"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 2.8.1
          architecture: x64
          cache: false
          pub-cache-path: default
          dry-run: false
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        run: flutter build appbundle
