name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 2.8.1
          architecture: x64
          cache: false
          pub-cache-path: default
          dry-run: false
      - name: Upgrade SDK
        run: flutter upgrade
      - name: Get dependencies
        run: flutter pub get
      - name: Create .env file
        run: |
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}" > .env
      - name: Start release build
        run: flutter build appbundle
