name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 2.8.1
          architecture: x64
          cache: false
          pub-cache-path: default
          dry-run: false
      - name: Upgrade SDK
        run: flutter upgrade
      - name: Get dependencies
        run: flutter pub get
      - name: Create .env file
        run: |
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}" > .env
      - name: Start release build
        run: flutter build appbundle
      - name: Build APK
        run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/ 

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: ./app-release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: app-release
          release_name: fin.it release
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
