name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: dart-lang/setup-dart@v1.6.4 # Correct action and version
        with:
          dart-sdk-version: '3.0.6' # Specify the Dart SDK version here
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 2.8.1 # Specify the Flutter version here
          architecture: x64
          cache: false
          pub-cache-path: default
          dry-run: false
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        run: flutter build appbundle
